### ISSUE TITLE
Please add RSS feed

### ISSUE THREAD

**Issue by dvhwgumby** [mlerner/mlerner.github.io#5]
Your page doesn't have Hugo's RSS publishing enabled.

**Comment by mlerner** [comment]
Thanks for pointing this out - I attempted to add an Atom feed here: https://www.micahlerner.com/feed.xml

Can you let me know if that works for you @dvhwgumby?

**Comment by mlerner** [comment]
Closing this ticket as the feed is reported working by other users: https://news.ycombinator.com/item?id=27952132
